---
{
   "kind": "pipeline",
   "name": "scala-jsonschema/2.13",
   "steps": [
      {
         "commands": [
            "CI=Drone SCALA_VER=2.13 sbt clean test"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov_token"
            }
         },
         "image": "andyglow/sbt:latest",
         "name": "build_2.13",
         "when": {
            "branch": "master"
         }
      }
   ],
   "type": "docker",
   "workspace": {
      "path": "2.13"
   }
}
---
{
   "kind": "pipeline",
   "name": "scala-jsonschema/2.12",
   "steps": [
      {
         "commands": [
            "CI=Drone SCALA_VER=2.12 sbt clean test"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov_token"
            }
         },
         "image": "andyglow/sbt:latest",
         "name": "build_2.12",
         "when": {
            "branch": "master"
         }
      }
   ],
   "type": "docker",
   "workspace": {
      "path": "2.12"
   }
}
---
{
   "kind": "pipeline",
   "name": "scala-jsonschema/2.11",
   "steps": [
      {
         "commands": [
            "CI=Drone SCALA_VER=2.11 sbt clean test"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov_token"
            }
         },
         "image": "andyglow/sbt:latest",
         "name": "build_2.11",
         "when": {
            "branch": "master"
         }
      }
   ],
   "type": "docker",
   "workspace": {
      "path": "2.11"
   }
}
---
{
   "depends_on": [
      "scala-jsonschema/2.13",
      "scala-jsonschema/2.12",
      "scala-jsonschema/2.11"
   ],
   "kind": "pipeline",
   "name": "scala-jsonschema/finalize",
   "steps": [
      {
         "commands": [
            "CI=Drone SCALA_VER=2.13 sbt clean coverage test",
            "CI=Drone SCALA_VER=2.13 sbt coverageAggregate",
            "wget -O .codecov https://codecov.io/bash",
            "chmod +x .codecov",
            "./.codecov -X gcov -X coveragepy -X xcode -X gcovout"
         ],
         "environment": {
            "CODECOV_TOKEN": {
               "from_secret": "codecov_token"
            }
         },
         "image": "andyglow/sbt:latest",
         "name": "scoverage",
         "when": {
            "branch": "master"
         }
      },
      {
         "depends_on": [
            "scoverage"
         ],
         "image": "plugins/slack",
         "name": "slack",
         "settings": {
            "channel": "builds",
            "link_names": true,
            "template": "{{#success build.status}}\n  {{repo.name}}: build {{build.number}} succeeded (spent {{since build.started}}). Good job. {{build.link}}\n{{else}}\n  {{repo.name}}: build {{build.number}} failed. Fix please. {{build.link}}\n{{/success}}\n",
            "username": "drone",
            "webhook": {
               "from_secret": "slack_webhook_url"
            }
         },
         "when": {
            "status": [
               "success",
               "failure"
            ]
         }
      }
   ],
   "type": "docker",
   "workspace": {
      "path": "finalize"
   }
}
...
